#!/bin/sh

su ec2-user /home/ec2-user/scripts/ec2-backup.sh >/dev/null 2>&1

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t ec2-backup "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
